export const ITALIAN_JAPANESE_DEVELOPER_COPY = {
  empty: ['— vuoto —', '— 空 —'],
  uncaughtException: ['Eccezione non gestita', '未処理の例外'],
  logEntry: ['Voce di log', 'ログ項目'],
  requestFailed: ['Richiesta non riuscita', 'リクエスト失敗'],
  performanceRefreshFailed: ['Aggiornamento delle prestazioni non riuscito', 'パフォーマンスを更新できませんでした'],
  domRefreshed: ['Istantanea DOM aggiornata.', 'DOM スナップショットを更新しました。'],
  domRefreshFailed: ['Aggiornamento DOM non riuscito', 'DOM を更新できませんでした'],
  nodeInspectFailed: ['Ispezione del nodo non riuscita', 'ノードを検査できませんでした'],
  storageRefreshFailed: ['Aggiornamento dell’archiviazione del sito non riuscito', 'サイトストレージを更新できませんでした'],
  siteInfoRefreshFailed: ['Aggiornamento delle informazioni del sito non riuscito', 'サイト情報を更新できませんでした'],
  inspectorAttached: ['Inspector collegato · eventi live attivi.', 'Inspector を接続しました · ライブイベントが有効です。'],
  inspectorAttachFailed: ['Collegamento dell’Inspector non riuscito', 'Inspector を接続できませんでした'],
  evaluationFailed: ['Valutazione non riuscita', '評価に失敗しました'],
  actionProgress: [
    (label: string) => `${label}…`,
    (label: string) => `${label}…`,
  ],
  actionComplete: [
    (label: string) => `${label} completato.`,
    (label: string) => `${label}が完了しました。`,
  ],
  actionFailed: [
    (label: string) => `${label} non riuscito`,
    (label: string) => `${label}に失敗しました`,
  ],
  clearedSiteStorage: [
    (origin: string) => `Dati del sito cancellati per ${origin}.`,
    (origin: string) => `${origin} のサイトストレージを消去しました。`,
  ],
  clearSiteStorageFailed: ['Cancellazione dei dati del sito non riuscita', 'サイトストレージを消去できませんでした'],
  titleAria: ['Strumenti per sviluppatori Nebula', 'Nebula 開発者ツール'],
  inspector: ['Nebula Inspector', 'Nebula Inspector'],
  noActiveWebview: ['Nessuna WebView attiva', 'アクティブな WebView はありません'],
  noActiveUrl: ['Nessun URL attivo', 'アクティブな URL はありません'],
  closeAria: ['Chiudi gli strumenti per sviluppatori', '開発者ツールを閉じる'],
  closeTitle: ['Chiudi (F12 / Esc)', '閉じる（F12 / Esc）'],
  overview: ['Panoramica', '概要'],
  elements: ['Elementi', '要素'],
  console: ['Console', 'コンソール'],
  network: ['Rete', 'ネットワーク'],
  performance: ['Prestazioni', 'パフォーマンス'],
  storage: ['Archiviazione', 'ストレージ'],
  site: ['Sito', 'サイト'],
  sources: ['Sorgenti', 'ソース'],
  accessibility: ['Accessibilità', 'アクセシビリティ'],
  events: ['Eventi', 'イベント'],
  openTabHint: ['Apri una scheda del browser per collegare Nebula Inspector.', 'ブラウザーのタブを開いて Nebula Inspector を接続してください。'],
  overviewLead: ['Stato live della WebView nativa attiva.', 'アクティブなネイティブ WebView のライブ状態。'],
  refresh: ['Aggiorna', '更新'],
  activeTab: ['Scheda attiva', 'アクティブなタブ'],
  openTabs: ['Schede aperte', '開いているタブ'],
  memoryPressure: ['Pressione memoria', 'メモリ負荷'],
  audio: ['Audio', '音声'],
  playing: ['In riproduzione', '再生中'],
  silent: ['Silenzioso', '無音'],
  security: ['Sicurezza', 'セキュリティ'],
  consoleErrors: ['Errori console', 'コンソールエラー'],
  requests: ['Richieste', 'リクエスト'],
  failedRequests: ['Richieste non riuscite', '失敗したリクエスト'],
  blockedRequests: ['Richieste bloccate', 'ブロックされたリクエスト'],
  currentUrl: ['URL corrente', '現在の URL'],
  reload: ['Ricarica', '再読み込み'],
  reloadHint: ['Ricarica la WebView attiva', 'アクティブな WebView を再読み込み'],
  clearCache: ['Cancella cache', 'キャッシュを消去'],
  clearCacheHint: ['Cancella la cache della scheda attiva', 'アクティブなタブのキャッシュを消去'],
  clearBuffers: ['Cancella buffer dell’Inspector', 'Inspector のバッファーを消去'],
  clearBuffersHint: ['Cronologia di console, rete ed eventi', 'コンソール、ネットワーク、イベントの履歴'],
  buffersCleared: ['Buffer dell’Inspector cancellati.', 'Inspector のバッファーを消去しました。'],
  dom: ['DOM', 'DOM'],
  loading: ['Caricamento…', '読み込み中…'],
  noDom: ['Nessuna istantanea DOM.', 'DOM スナップショットはまだありません。'],
  nodeDetails: ['Dettagli nodo', 'ノードの詳細'],
  clearHighlight: ['Rimuovi evidenziazione', 'ハイライトを解除'],
  inspectElement: ['Seleziona elemento dalla pagina', 'ページから要素を選択'],
  stopInspecting: ['Interrompi selezione', '選択を停止'],
  inspectHint: ['Passa il puntatore sulla pagina e fai clic sull’elemento da ispezionare.', 'ページ上でマウスを動かし、検査する要素をクリックしてください。'],
  outerHtml: ['HTML esterno', 'Outer HTML'],
  editHtml: ['Modifica HTML', 'HTML を編集'],
  apply: ['Applica', '適用'],
  cancel: ['Annulla', 'キャンセル'],
  copy: ['Copia', 'コピー'],
  attributeName: ['Nome attributo', '属性名'],
  attributeValue: ['Valore attributo', '属性値'],
  setAttribute: ['Aggiungi / aggiorna', '追加 / 更新'],
  removeAttribute: ['Rimuovi', '削除'],
  searchDom: ['Cerca selettore CSS, XPath o testo…', 'CSS セレクター、XPath、テキストを検索…'],
  search: ['Cerca', '検索'],
  previousMatch: ['Precedente', '前へ'],
  nextMatch: ['Successivo', '次へ'],
  noMatches: ['Nessuna corrispondenza', '一致なし'],
  filterStyles: ['Filtra stili calcolati…', '計算済みスタイルを絞り込む…'],
  computedStyles: ['Stili calcolati', '計算済みスタイル'],
  selectNode: ['Seleziona un nodo DOM per ispezionarne HTML e stili calcolati.', 'DOM ノードを選択して HTML と計算済みスタイルを検査します。'],
  filterConsole: ['Filtra console…', 'コンソールを絞り込む…'],
  allLevels: ['Tutti i livelli', 'すべてのレベル'],
  edit: ['Modifica', '編集'],
  command: ['Comando', 'コマンド'],
  result: ['Risultato', '結果'],
  protocol: ['Protocollo', 'プロトコル'],
  remote: ['Remoto', 'リモート'],
  cache: ['Cache', 'キャッシュ'],
  request: ['Richiesta', 'リクエスト'],
  initiatorSecurity: ['Iniziatore / Sicurezza', '開始元 / セキュリティ'],
  cdpMetrics: ['Metriche CDP', 'CDP 指標'],
  clear: ['Cancella', '消去'],
  consoleQuiet: ['La console è vuota.', 'コンソールは静かです。'],
  evalPlaceholder: ['Valuta JavaScript nella pagina attiva…', 'アクティブなページで JavaScript を評価…'],
  run: ['Esegui', '実行'],
  filterNetwork: ['Filtra URL, metodo, stato o tipo…', 'URL、メソッド、ステータス、種類を絞り込む…'],
  failed: ['non riuscite', '失敗'],
  blocked: ['bloccate', 'ブロック'],
  status: ['Stato', 'ステータス'],
  method: ['Metodo', 'メソッド'],
  type: ['Tipo', '種類'],
  time: ['Tempo', '時間'],
  size: ['Dimensione', 'サイズ'],
  other: ['Altro', 'その他'],
  noRequests: ['Nessuna richiesta acquisita dall’apertura dell’Inspector.', 'Inspector を開いてからリクエストは取得されていません。'],
  recording: ['Registrazione', '記録中'],
  preserveLog: ['Mantieni log', 'ログを保持'],
  disableCache: ['Disattiva cache', 'キャッシュを無効化'],
  requestDetails: ['Dettagli richiesta', 'リクエストの詳細'],
  headers: ['Intestazioni', 'ヘッダー'],
  payload: ['Payload richiesta', 'リクエスト ペイロード'],
  response: ['Risposta', 'レスポンス'],
  preview: ['Anteprima', 'プレビュー'],
  copyUrl: ['Copia URL', 'URL をコピー'],
  copyCurl: ['Copia come cURL', 'cURL としてコピー'],
  noResponseBody: ['Il corpo della risposta non è disponibile o non è ancora pronto.', 'レスポンス本文がないか、まだ準備できていません。'],
  performanceLead: ['Contatori delle prestazioni CDP e utilizzo dell’heap V8.', 'CDP パフォーマンスカウンターと V8 ヒープ使用量。'],
  heapUsed: ['Heap JS usato', '使用中の JS ヒープ'],
  heapTotal: ['Heap JS totale', 'JS ヒープ合計'],
  capturedMetrics: ['Metriche acquisite', '取得した指標'],
  pageDomNodes: ['Nodi DOM della pagina', 'ページの DOM ノード'],
  resourceTimingEntries: ['Voci Resource Timing', 'Resource Timing エントリ'],
  resourceTimingTransfer: ['Trasferimento Resource Timing', 'Resource Timing 転送量'],
  resourceTimingDecoded: ['Corpo decodificato Resource Timing', 'Resource Timing デコード後本文'],
  autoRefresh: ['Aggiornamento automatico', '自動更新'],
  pageSummary: ['Riepilogo pagina', 'ページ概要'],
  nebulaStorage: ['Archiviazione Nebula', 'Nebula ストレージ'],
  nebulaStorageLead: ['Stato localStorage della shell del browser.', 'ブラウザーシェルの localStorage 状態。'],
  clearFolderCache: ['Cancella cache cartelle', 'フォルダーキャッシュを消去'],
  clearLayout: ['Cancella layout', 'レイアウトを消去'],
  delete: ['Elimina', '削除'],
  noNebulaStorage: ['Nessuna voce nel localStorage di Nebula.', 'Nebula の localStorage 項目はありません。'],
  pageStorage: ['Archiviazione pagina', 'ページストレージ'],
  pageStorageLead: ['Archiviazione locale/di sessione e metadati dei cookie del sito attivo.', 'アクティブなサイトのローカル/セッションストレージと Cookie メタデータ。'],
  noPageStorage: ['Nessuna istantanea dell’archiviazione della pagina.', 'ページストレージのスナップショットはありません。'],
  storageArea: ['Area', '領域'],
  storageKey: ['Chiave', 'キー'],
  storageValue: ['Valore', '値'],
  setStorageValue: ['Salva', '保存'],
  cacheStorage: ['Cache Storage', 'Cache Storage'],
  indexedDb: ['IndexedDB', 'IndexedDB'],
  serviceWorkers: ['Service Worker', 'Service Worker'],
  deleteCookie: ['Elimina cookie', 'Cookie を削除'],
  cookieValue: ['Valore cookie', 'Cookie の値'],
  showCookieValue: ['Mostra valore', '値を表示'],
  hideCookieValue: ['Nascondi valore', '値を非表示'],
  unspecified: ['Non specificato', '未指定'],
  clearCurrentSite: ['Cancella dati del sito corrente', '現在のサイトデータを消去'],
  clearCurrentSiteHint: ['Cookie, archiviazione e cache dell’origine corrente', '現在のオリジンの Cookie、ストレージ、キャッシュ'],
  siteLead: ['Identità, sicurezza e stato delle autorizzazioni della pagina.', 'ページの識別情報、セキュリティ、権限の状態。'],
  readyState: ['Stato di caricamento', '読み込み状態'],
  visibility: ['Visibilità', '表示状態'],
  online: ['Online', 'オンライン'],
  cookies: ['Cookie', 'Cookie'],
  cookieApi: ['API Cookie', 'Cookie API'],
  cookieApiAvailable: ['Disponibile', '利用可能'],
  cookieApiUnavailable: ['Non disponibile', '利用不可'],
  siteCookies: ['Cookie del sito', 'サイトの Cookie'],
  nebulaCookiePolicy: ['Criterio Nebula per i cookie tra siti', 'Nebula のクロスサイト Cookie ポリシー'],
  strictPolicy: ['Rigido · invio dei cookie bloccato', '厳格 · Cookie の送信をブロック'],
  standardPolicy: ['Standard · nessun filtro Nebula aggiuntivo', '標準 · Nebula の追加フィルターなし'],
  trackingPrevention: ['Prevenzione del tracciamento', '追跡防止'],
  trackerBlocking: ['Blocco dei tracker', 'トラッカーのブロック'],
  trackingNone: ['Disattivato', 'オフ'],
  trackingBalanced: ['Bilanciato', 'バランス'],
  trackingStrict: ['Rigido', '厳格'],
  historyLength: ['Lunghezza cronologia', '履歴の長さ'],
  yes: ['Sì', 'はい'],
  no: ['No', 'いいえ'],
  enabled: ['Attivato', '有効'],
  disabled: ['Disattivato', '無効'],
  title: ['Titolo', 'タイトル'],
  origin: ['Origine', 'オリジン'],
  language: ['Lingua', '言語'],
  charset: ['Set di caratteri', '文字セット'],
  referrer: ['Referrer', '参照元'],
  viewport: ['Viewport', 'ビューポート'],
  permissions: ['Autorizzazioni', '権限'],
  filterSources: ['Filtra URL degli script…', 'スクリプト URL を絞り込む…'],
  showAnonymousSources: ['Mostra script anonimi', '匿名スクリプトを表示'],
  anonymousScripts: ['Script anonimi', '匿名スクリプト'],
  inlineScripts: ['Script inline / virtuali', 'インライン / 仮想スクリプト'],
  noSources: ['Nessuno script acquisito.', '取得したスクリプトはまだありません。'],
  noSourceMatches: ['Nessuno script corrisponde al filtro e alle impostazioni di visibilità.', 'フィルターと表示設定に一致するスクリプトはありません。'],
  selectSource: ['Seleziona uno script a sinistra per visualizzarne il codice sorgente.', '左側のスクリプトを選択してソースコードを表示します。'],
  sourceCode: ['Codice sorgente', 'ソースコード'],
  accessibilityLead: ['Albero di accessibilità e corrispondenze DOM della pagina attiva.', 'アクティブなページのアクセシビリティツリーと DOM の対応。'],
  filterAccessibility: ['Filtra per ruolo, nome, descrizione o ID DOM…', 'ロール、名前、説明、DOM ID で絞り込む…'],
  showAccessibilityNoise: ['Mostra nodi ignorati e vuoti', '無視された空のノードを表示'],
  noAccessibility: ['Nessun nodo di accessibilità trovato.', 'アクセシビリティノードが見つかりませんでした。'],
  noAccessibilityMatches: ['Nessun nodo di accessibilità corrisponde al filtro.', 'フィルターに一致するアクセシビリティノードはありません。'],
  filterEvents: ['Filtra eventi CDP…', 'CDP イベントを絞り込む…'],
  buffered: ['nel buffer', 'バッファー済み'],
  noEvents: ['Nessun evento CDP corrispondente.', '一致する CDP イベントはありません。'],
  closeFooter: ['F12 / Esc per chiudere', 'F12 / Esc で閉じる'],
  cdpInspector: ['Nebula Inspector basato su CDP', 'CDP ベースの Nebula Inspector'],
  waitingTab: ['In attesa di una scheda', 'タブを待機中'],
} as const
