export const ADDITIONAL_DEVELOPER_COPY = {
  empty: ['— vide —', '— kosong —', '— пусто —'],
  uncaughtException: ['Exception non interceptée', 'Pengecualian tidak tertangkap', 'Необработанное исключение'],
  logEntry: ['Entrée de journal', 'Entri log', 'Запись журнала'],
  requestFailed: ['Échec de la requête', 'Permintaan gagal', 'Сбой запроса'],
  performanceRefreshFailed: ['Échec de l’actualisation des performances', 'Gagal memperbarui performa', 'Не удалось обновить данные производительности'],
  domRefreshed: ['Instantané du DOM actualisé.', 'Snapshot DOM diperbarui.', 'Снимок DOM обновлён.'],
  domRefreshFailed: ['Échec de l’actualisation du DOM', 'Gagal memperbarui DOM', 'Не удалось обновить DOM'],
  nodeInspectFailed: ['Échec de l’inspection du nœud', 'Gagal memeriksa node', 'Не удалось исследовать узел'],
  storageRefreshFailed: ['Échec de l’actualisation du stockage du site', 'Gagal memperbarui penyimpanan situs', 'Не удалось обновить хранилище сайта'],
  siteInfoRefreshFailed: ['Échec de l’actualisation des informations du site', 'Gagal memperbarui informasi situs', 'Не удалось обновить сведения о сайте'],
  inspectorAttached: ['Inspector connecté · événements en direct activés.', 'Inspector terhubung · peristiwa langsung aktif.', 'Inspector подключён · события в реальном времени включены.'],
  inspectorAttachFailed: ['Échec de la connexion de l’Inspector', 'Gagal menghubungkan Inspector', 'Не удалось подключить Inspector'],
  evaluationFailed: ['Échec de l’évaluation', 'Evaluasi gagal', 'Ошибка вычисления'],
  actionProgress: [
    (label: string) => `${label}…`,
    (label: string) => `${label}…`,
    (label: string) => `${label}…`,
  ],
  actionComplete: [
    (label: string) => `${label} terminé.`,
    (label: string) => `${label} selesai.`,
    (label: string) => `${label}: выполнено.`,
  ],
  actionFailed: [
    (label: string) => `Échec de l’action « ${label} »`,
    (label: string) => `${label} gagal`,
    (label: string) => `${label}: ошибка`,
  ],
  clearedSiteStorage: [
    (origin: string) => `Données du site effacées pour ${origin}.`,
    (origin: string) => `Penyimpanan situs untuk ${origin} dihapus.`,
    (origin: string) => `Данные сайта ${origin} удалены.`,
  ],
  clearSiteStorageFailed: ['Échec de l’effacement des données du site', 'Gagal menghapus penyimpanan situs', 'Не удалось удалить данные сайта'],
  titleAria: ['Outils de développement Nebula', 'Alat Pengembang Nebula', 'Инструменты разработчика Nebula'],
  inspector: ['Inspector Nebula', 'Nebula Inspector', 'Nebula Inspector'],
  noActiveWebview: ['Aucune WebView active', 'Tidak ada WebView aktif', 'Нет активного WebView'],
  noActiveUrl: ['Aucune URL active', 'Tidak ada URL aktif', 'Нет активного URL'],
  closeAria: ['Fermer les outils de développement', 'Tutup alat pengembang', 'Закрыть инструменты разработчика'],
  closeTitle: ['Fermer (F12 / Échap)', 'Tutup (F12 / Esc)', 'Закрыть (F12 / Esc)'],
  overview: ['Vue d’ensemble', 'Ringkasan', 'Обзор'],
  elements: ['Éléments', 'Elemen', 'Элементы'],
  console: ['Console', 'Konsol', 'Консоль'],
  network: ['Réseau', 'Jaringan', 'Сеть'],
  performance: ['Performances', 'Performa', 'Производительность'],
  storage: ['Stockage', 'Penyimpanan', 'Хранилище'],
  site: ['Site', 'Situs', 'Сайт'],
  sources: ['Sources', 'Sumber', 'Исходный код'],
  accessibility: ['Accessibilité', 'Aksesibilitas', 'Специальные возможности'],
  events: ['Événements', 'Peristiwa', 'События'],
  openTabHint: ['Ouvrez un onglet pour connecter l’Inspector Nebula.', 'Buka tab browser untuk menghubungkan Nebula Inspector.', 'Откройте вкладку браузера, чтобы подключить Nebula Inspector.'],
  overviewLead: ['État en direct de la WebView native active.', 'Status langsung WebView native yang aktif.', 'Состояние активного нативного WebView в реальном времени.'],
  refresh: ['Actualiser', 'Perbarui', 'Обновить'],
  activeTab: ['Onglet actif', 'Tab aktif', 'Активная вкладка'],
  openTabs: ['Onglets ouverts', 'Tab terbuka', 'Открытые вкладки'],
  memoryPressure: ['Pression mémoire', 'Tekanan memori', 'Нагрузка на память'],
  audio: ['Audio', 'Audio', 'Аудио'],
  playing: ['Lecture', 'Memutar', 'Воспроизведение'],
  silent: ['Silencieux', 'Hening', 'Без звука'],
  security: ['Sécurité', 'Keamanan', 'Безопасность'],
  consoleErrors: ['Erreurs de console', 'Error konsol', 'Ошибки консоли'],
  requests: ['Requêtes', 'Permintaan', 'Запросы'],
  failedRequests: ['Requêtes échouées', 'Permintaan gagal', 'Неудачные запросы'],
  blockedRequests: ['Requêtes bloquées', 'Permintaan diblokir', 'Заблокированные запросы'],
  currentUrl: ['URL actuelle', 'URL saat ini', 'Текущий URL'],
  reload: ['Recharger', 'Muat ulang', 'Перезагрузить'],
  reloadHint: ['Recharger la WebView active', 'Muat ulang WebView aktif', 'Перезагрузить активный WebView'],
  clearCache: ['Vider le cache', 'Hapus cache', 'Очистить кэш'],
  clearCacheHint: ['Vider le cache de l’onglet actif', 'Hapus cache tab aktif', 'Очистить кэш активной вкладки'],
  clearBuffers: ['Vider les tampons de l’Inspector', 'Hapus buffer Inspector', 'Очистить буферы Inspector'],
  clearBuffersHint: ['Historique de la console, du réseau et des événements', 'Riwayat konsol, jaringan, dan peristiwa', 'История консоли, сети и событий'],
  buffersCleared: ['Tampons de l’Inspector vidés.', 'Buffer Inspector dihapus.', 'Буферы Inspector очищены.'],
  dom: ['DOM', 'DOM', 'DOM'],
  loading: ['Chargement…', 'Memuat…', 'Загрузка…'],
  noDom: ['Aucun instantané du DOM pour le moment.', 'Belum ada snapshot DOM.', 'Снимка DOM пока нет.'],
  nodeDetails: ['Détails du nœud', 'Detail node', 'Сведения об узле'],
  clearHighlight: ['Effacer la surbrillance', 'Hapus sorotan', 'Убрать выделение'],
  inspectElement: ['Sélectionner un élément dans la page', 'Pilih elemen dari halaman', 'Выбрать элемент на странице'],
  stopInspecting: ['Arrêter la sélection', 'Hentikan pemilihan', 'Остановить выбор'],
  inspectHint: ['Survolez la page et cliquez sur l’élément à inspecter.', 'Arahkan ke halaman lalu klik elemen yang ingin diperiksa.', 'Наведите указатель на страницу и щёлкните элемент, который хотите исследовать.'],
  outerHtml: ['HTML externe', 'HTML luar', 'Внешний HTML'],
  editHtml: ['Modifier le HTML', 'Edit HTML', 'Изменить HTML'],
  apply: ['Appliquer', 'Terapkan', 'Применить'],
  cancel: ['Annuler', 'Batal', 'Отмена'],
  copy: ['Copier', 'Salin', 'Копировать'],
  attributeName: ['Nom de l’attribut', 'Nama atribut', 'Имя атрибута'],
  attributeValue: ['Valeur de l’attribut', 'Nilai atribut', 'Значение атрибута'],
  setAttribute: ['Ajouter / mettre à jour', 'Tambah / perbarui', 'Добавить / обновить'],
  removeAttribute: ['Supprimer', 'Hapus', 'Удалить'],
  searchDom: ['Rechercher un sélecteur CSS, XPath ou du texte…', 'Cari pemilih CSS, XPath, atau teks…', 'Поиск по CSS-селектору, XPath или тексту…'],
  search: ['Rechercher', 'Cari', 'Поиск'],
  previousMatch: ['Précédent', 'Sebelumnya', 'Предыдущее'],
  nextMatch: ['Suivant', 'Berikutnya', 'Следующее'],
  noMatches: ['Aucun résultat', 'Tidak ada kecocokan', 'Нет совпадений'],
  filterStyles: ['Filtrer les styles calculés…', 'Filter gaya terhitung…', 'Фильтр вычисленных стилей…'],
  computedStyles: ['Styles calculés', 'Gaya terhitung', 'Вычисленные стили'],
  selectNode: ['Sélectionnez un nœud DOM pour inspecter son HTML et ses styles calculés.', 'Pilih node DOM untuk memeriksa HTML dan gaya terhitungnya.', 'Выберите узел DOM, чтобы исследовать HTML и вычисленные стили.'],
  filterConsole: ['Filtrer la console…', 'Filter konsol…', 'Фильтр консоли…'],
  allLevels: ['Tous les niveaux', 'Semua level', 'Все уровни'],
  edit: ['Modifier', 'Edit', 'Изменить'],
  command: ['Commande', 'Perintah', 'Команда'],
  result: ['Résultat', 'Hasil', 'Результат'],
  protocol: ['Protocole', 'Protokol', 'Протокол'],
  remote: ['Adresse distante', 'Alamat jarak jauh', 'Удалённый адрес'],
  cache: ['Cache', 'Cache', 'Кэш'],
  request: ['Requête', 'Permintaan', 'Запрос'],
  initiatorSecurity: ['Initiateur / Sécurité', 'Pemicu / Keamanan', 'Инициатор / Безопасность'],
  cdpMetrics: ['Métriques CDP', 'Metrik CDP', 'Метрики CDP'],
  clear: ['Effacer', 'Hapus', 'Очистить'],
  consoleQuiet: ['La console est vide.', 'Konsol kosong.', 'Консоль пуста.'],
  evalPlaceholder: ['Évaluer du JavaScript dans la page active…', 'Evaluasi JavaScript di halaman aktif…', 'Выполнить JavaScript на активной странице…'],
  run: ['Exécuter', 'Jalankan', 'Выполнить'],
  filterNetwork: ['Filtrer par URL, méthode, état ou type…', 'Filter URL, metode, status, atau jenis…', 'Фильтр по URL, методу, состоянию или типу…'],
  failed: ['échec', 'gagal', 'ошибка'],
  blocked: ['bloquée', 'diblokir', 'заблокирован'],
  status: ['État', 'Status', 'Состояние'],
  method: ['Méthode', 'Metode', 'Метод'],
  type: ['Type', 'Jenis', 'Тип'],
  time: ['Durée', 'Waktu', 'Время'],
  size: ['Taille', 'Ukuran', 'Размер'],
  other: ['Autre', 'Lainnya', 'Другое'],
  noRequests: ['Aucune requête capturée depuis l’ouverture de l’Inspector.', 'Tidak ada permintaan yang ditangkap sejak Inspector dibuka.', 'С момента открытия Inspector запросы не зафиксированы.'],
  recording: ['Enregistrement', 'Merekam', 'Запись'],
  preserveLog: ['Conserver le journal', 'Pertahankan log', 'Сохранять журнал'],
  disableCache: ['Désactiver le cache', 'Nonaktifkan cache', 'Отключить кэш'],
  requestDetails: ['Détails de la requête', 'Detail permintaan', 'Сведения о запросе'],
  headers: ['En-têtes', 'Header', 'Заголовки'],
  payload: ['Corps de la requête', 'Payload permintaan', 'Данные запроса'],
  response: ['Réponse', 'Respons', 'Ответ'],
  preview: ['Aperçu', 'Pratinjau', 'Предпросмотр'],
  copyUrl: ['Copier l’URL', 'Salin URL', 'Копировать URL'],
  copyCurl: ['Copier comme cURL', 'Salin sebagai cURL', 'Копировать как cURL'],
  noResponseBody: ['Le corps de la réponse est absent ou n’est pas encore prêt.', 'Tidak ada isi respons atau belum siap.', 'Тело ответа отсутствует или ещё не готово.'],
  performanceLead: ['Compteurs de performances CDP et utilisation du tas V8.', 'Penghitung performa CDP dan penggunaan heap V8.', 'Счётчики производительности CDP и использование кучи V8.'],
  heapUsed: ['Tas JS utilisé', 'Heap JS terpakai', 'Использовано кучи JS'],
  heapTotal: ['Tas JS total', 'Total heap JS', 'Общий объём кучи JS'],
  capturedMetrics: ['Métriques capturées', 'Metrik tertangkap', 'Полученные метрики'],
  pageDomNodes: ['Nœuds DOM de la page', 'Node DOM halaman', 'Узлы DOM страницы'],
  resourceTimingEntries: ['Entrées Resource Timing', 'Entri Resource Timing', 'Записи Resource Timing'],
  resourceTimingTransfer: ['Transfert Resource Timing', 'Transfer Resource Timing', 'Передача Resource Timing'],
  resourceTimingDecoded: ['Corps décodé Resource Timing', 'Isi terdekode Resource Timing', 'Декодированное тело Resource Timing'],
  autoRefresh: ['Actualisation automatique', 'Perbarui otomatis', 'Автообновление'],
  pageSummary: ['Résumé de la page', 'Ringkasan halaman', 'Сводка страницы'],
  nebulaStorage: ['Stockage Nebula', 'Penyimpanan Nebula', 'Хранилище Nebula'],
  nebulaStorageLead: ['État du localStorage de l’interface du navigateur.', 'Status localStorage shell browser.', 'Состояние localStorage оболочки браузера.'],
  clearFolderCache: ['Vider le cache des dossiers', 'Hapus cache folder', 'Очистить кэш папок'],
  clearLayout: ['Effacer la disposition', 'Hapus tata letak', 'Сбросить расположение'],
  delete: ['Supprimer', 'Hapus', 'Удалить'],
  noNebulaStorage: ['Aucune entrée dans le localStorage de Nebula.', 'Tidak ada entri localStorage Nebula.', 'В localStorage Nebula нет записей.'],
  pageStorage: ['Stockage de la page', 'Penyimpanan halaman', 'Хранилище страницы'],
  pageStorageLead: ['Stockages local/de session et métadonnées des cookies du site actif.', 'Penyimpanan lokal/sesi dan metadata cookie situs aktif.', 'Локальное/сеансовое хранилище и метаданные cookie активного сайта.'],
  noPageStorage: ['Aucun instantané du stockage de la page.', 'Tidak ada snapshot penyimpanan halaman.', 'Снимок хранилища страницы отсутствует.'],
  storageArea: ['Zone', 'Area', 'Область'],
  storageKey: ['Clé', 'Kunci', 'Ключ'],
  storageValue: ['Valeur', 'Nilai', 'Значение'],
  setStorageValue: ['Enregistrer', 'Simpan', 'Сохранить'],
  cacheStorage: ['Cache Storage', 'Cache Storage', 'Cache Storage'],
  indexedDb: ['IndexedDB', 'IndexedDB', 'IndexedDB'],
  serviceWorkers: ['Service Workers', 'Service Worker', 'Service Workers'],
  deleteCookie: ['Supprimer le cookie', 'Hapus cookie', 'Удалить cookie'],
  cookieValue: ['Valeur du cookie', 'Nilai cookie', 'Значение cookie'],
  showCookieValue: ['Afficher la valeur', 'Tampilkan nilai', 'Показать значение'],
  hideCookieValue: ['Masquer la valeur', 'Sembunyikan nilai', 'Скрыть значение'],
  unspecified: ['Non spécifié', 'Tidak ditentukan', 'Не указано'],
  clearCurrentSite: ['Effacer les données du site actuel', 'Hapus data situs saat ini', 'Удалить данные текущего сайта'],
  clearCurrentSiteHint: ['Cookies, stockage et cache de l’origine actuelle', 'Cookie, penyimpanan, dan cache untuk origin saat ini', 'Cookie, хранилище и кэш текущего источника'],
  siteLead: ['Identité de la page, sécurité et état des autorisations.', 'Identitas halaman, keamanan, dan status izin.', 'Идентификация страницы, безопасность и разрешения.'],
  readyState: ['État de chargement', 'Status kesiapan', 'Состояние готовности'],
  visibility: ['Visibilité', 'Visibilitas', 'Видимость'],
  online: ['En ligne', 'Online', 'В сети'],
  cookies: ['Cookies', 'Cookie', 'Cookie'],
  cookieApi: ['API Cookie', 'API Cookie', 'API Cookie'],
  cookieApiAvailable: ['Disponible', 'Tersedia', 'Доступен'],
  cookieApiUnavailable: ['Indisponible', 'Tidak tersedia', 'Недоступен'],
  siteCookies: ['Cookies du site', 'Cookie situs', 'Cookie сайта'],
  nebulaCookiePolicy: ['Politique Nebula des cookies intersites', 'Kebijakan cookie lintas situs Nebula', 'Политика Nebula для межсайтовых cookie'],
  strictPolicy: ['Stricte · envoi des cookies bloqué', 'Ketat · pengiriman cookie diblokir', 'Строгая · отправка cookie заблокирована'],
  standardPolicy: ['Standard · aucun filtre Nebula supplémentaire', 'Standar · tanpa filter Nebula tambahan', 'Стандартная · без дополнительного фильтра Nebula'],
  trackingPrevention: ['Prévention du suivi', 'Pencegahan pelacakan', 'Защита от отслеживания'],
  trackerBlocking: ['Blocage des traqueurs', 'Pemblokiran pelacak', 'Блокировка трекеров'],
  trackingNone: ['Désactivée', 'Nonaktif', 'Отключена'],
  trackingBalanced: ['Équilibrée', 'Seimbang', 'Сбалансированная'],
  trackingStrict: ['Stricte', 'Ketat', 'Строгая'],
  historyLength: ['Longueur de l’historique', 'Panjang riwayat', 'Длина истории'],
  yes: ['Oui', 'Ya', 'Да'],
  no: ['Non', 'Tidak', 'Нет'],
  enabled: ['Activé', 'Aktif', 'Включено'],
  disabled: ['Désactivé', 'Nonaktif', 'Отключено'],
  title: ['Titre', 'Judul', 'Заголовок'],
  origin: ['Origine', 'Origin', 'Источник'],
  language: ['Langue', 'Bahasa', 'Язык'],
  charset: ['Jeu de caractères', 'Set karakter', 'Кодировка'],
  referrer: ['Référent', 'Perujuk', 'Источник перехода'],
  viewport: ['Zone d’affichage', 'Viewport', 'Область просмотра'],
  permissions: ['Autorisations', 'Izin', 'Разрешения'],
  filterSources: ['Filtrer les URL des scripts…', 'Filter URL skrip…', 'Фильтр URL скриптов…'],
  showAnonymousSources: ['Afficher les scripts anonymes', 'Tampilkan skrip anonim', 'Показывать анонимные скрипты'],
  anonymousScripts: ['Scripts anonymes', 'Skrip anonim', 'Анонимные скрипты'],
  inlineScripts: ['Scripts intégrés / virtuels', 'Skrip inline / virtual', 'Встроенные / виртуальные скрипты'],
  noSources: ['Aucun script capturé pour le moment.', 'Belum ada skrip yang ditangkap.', 'Скрипты пока не зафиксированы.'],
  noSourceMatches: ['Aucun script ne correspond au filtre et aux paramètres de visibilité.', 'Tidak ada skrip yang cocok dengan filter dan setelan visibilitas.', 'Нет скриптов, соответствующих фильтру и настройкам видимости.'],
  selectSource: ['Sélectionnez un script à gauche pour afficher son code source.', 'Pilih skrip di sebelah kiri untuk melihat kode sumbernya.', 'Выберите скрипт слева, чтобы просмотреть его исходный код.'],
  sourceCode: ['Code source', 'Kode sumber', 'Исходный код'],
  accessibilityLead: ['Arbre d’accessibilité et correspondances DOM de la page active.', 'Pohon aksesibilitas dan kecocokan DOM untuk halaman aktif.', 'Дерево специальных возможностей и совпадения DOM активной страницы.'],
  filterAccessibility: ['Filtrer par rôle, nom, description ou identifiant DOM…', 'Filter berdasarkan peran, nama, deskripsi, atau id DOM…', 'Фильтр по роли, имени, описанию или идентификатору DOM…'],
  showAccessibilityNoise: ['Afficher les nœuds ignorés et vides', 'Tampilkan node yang diabaikan dan kosong', 'Показывать игнорируемые и пустые узлы'],
  noAccessibility: ['Aucun nœud d’accessibilité trouvé.', 'Tidak ada node aksesibilitas.', 'Узлы специальных возможностей не найдены.'],
  noAccessibilityMatches: ['Aucun nœud d’accessibilité ne correspond au filtre.', 'Tidak ada node aksesibilitas yang cocok dengan filter.', 'Нет узлов специальных возможностей, соответствующих фильтру.'],
  filterEvents: ['Filtrer les événements CDP…', 'Filter peristiwa CDP…', 'Фильтр событий CDP…'],
  buffered: ['en mémoire tampon', 'dalam buffer', 'в буфере'],
  noEvents: ['Aucun événement CDP correspondant.', 'Tidak ada peristiwa CDP yang cocok.', 'Нет соответствующих событий CDP.'],
  closeFooter: ['F12 / Échap pour fermer', 'F12 / Esc untuk menutup', 'F12 / Esc — закрыть'],
  cdpInspector: ['Inspector Nebula basé sur CDP', 'Nebula Inspector berbasis CDP', 'Nebula Inspector на базе CDP'],
  waitingTab: ['En attente d’un onglet', 'Menunggu tab', 'Ожидание вкладки'],
} as const
